sudo: required
env:
  - DOCKER_IMAGE_NAME=cloudposse/github-authorized-keys
services:
- docker
install:
- make init
- make docker:login
- pip install docker-compose

script:
- |-
  export ETCD_IP=$(ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}')

- docker-compose -f docker-compose-test.yaml up -d

- |-
  docker build --tag test \
    --build-arg RUN_TESTS=1 \
    --build-arg TEST_GITHUB_API_TOKEN=${GITHUB_API_TOKEN} \
    --build-arg TEST_GITHUB_ORGANIZATION=${GITHUB_ORGANIZATION} \
    --build-arg TEST_GITHUB_TEAM=${GITHUB_TEAM} \
    --build-arg TEST_GITHUB_TEAM_ID=${GITHUB_TEAM_ID} \
    --build-arg TEST_GITHUB_USER=${GITHUB_USER} \
    --build-arg TEST_ETCD_ENDPOINT=http://${ETCD_IP}:2379 \
    ./

after_success:
- make docker:build
- make travis:docker-tag-and-push
