sudo: required
env:
  global:
    - DOCKER_IMAGE_NAME=cloudposse/github-authorized-keys
services:
  - docker

install:
  - make init
  - make docker:login
  - pip install docker-compose

script:
  - |-
    export ETCD_IP=$(ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}')

  - export TEST_ETCD_ENDPOINT=http://${ETCD_IP}:2379

# setup testing environment for etcd
  - make compose-up

# cross-compile & run tests
  - make ci

# build a slim alpine image that ships only with the release binary
  - make docker:build
 
after_success:
  - make travis:docker-tag-and-push

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file: "release/*"
  skip_cleanup: true
  on:
    tags: true
