sudo: required
language: go
go:
  - 1.7.x
env:
  global:
    - DOCKER_IMAGE_NAME=cloudposse/github-authorized-keys
    - RUN_TESTS=1
    - TEST_GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    - TEST_GITHUB_ORGANIZATION=${GITHUB_ORGANIZATION}
    - TEST_GITHUB_TEAM=${GITHUB_TEAM}
    - TEST_GITHUB_TEAM_ID=${GITHUB_TEAM_ID}
    - TEST_GITHUB_USER=${GITHUB_USER}
services:
  - docker

install:
  - make init
  - make docker:login
  - pip install docker-compose

script:
  - |-
    export ETCD_IP=$(ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}')

  - export TEST_ETCD_ENDPOINT=http://${ETCD_IP}:2379

  - docker-compose -f docker-compose-test.yaml up -d

  - |-
    make docker:build \
      ARGS="RUN_TESTS \
            TEST_GITHUB_API_TOKEN \
            TEST_GITHUB_ORGANIZATION \
            TEST_GITHUB_TEAM \
            TEST_GITHUB_TEAM_ID \
            TEST_GITHUB_USER \
            TEST_ETCD_ENDPOINT"
            
# Also build packages for release
  - make go:deps-dev
  - make go:deps-build
  - make go:deps
  - make go:build-all
  - ls -l release/

after_success:
  - make docker:build
  - make travis:docker-tag-and-push

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file: "release/*"
  skip_cleanup: true
  on:
    tags: true


