sudo: required
env:
  global:
    - DOCKER_IMAGE_NAME=cloudposse/github-authorized-keys
    - RUN_TESTS=1
    - TEST_GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    - TEST_GITHUB_ORGANIZATION=${GITHUB_ORGANIZATION}
    - TEST_GITHUB_TEAM=${GITHUB_TEAM}
    - TEST_GITHUB_TEAM_ID=${GITHUB_TEAM_ID}
    - TEST_GITHUB_USER=${GITHUB_USER}
    - TEST_ETCD_ENDPOINT=http://${ETCD_IP}:2379
services:
- docker
install:
- make init
- make docker:login
- pip install docker-compose

script:
- |-
  export ETCD_IP=$(ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}')

- docker-compose -f docker-compose-test.yaml up -d

- |-
  make docker:build \
    ARGS="RUN_TESTS \
          TEST_GITHUB_API_TOKEN \
          TEST_GITHUB_ORGANIZATION \
          TEST_GITHUB_TEAM \
          TEST_GITHUB_TEAM_ID \
          TEST_GITHUB_USER \
          TEST_ETCD_ENDPOINT \
          "

after_success:
- make docker:build
- make travis:docker-tag-and-push
