version: '2'

services:
  etcd:
    image: quay.io/coreos/etcd:v2.3.7
    command:
      - "--advertise-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001"
      - "--listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001"
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
      - "7001:7001"
    restart: always