version: '2'

services:
  github-authorized-keys:
    build: ./
    container_name: github-authorized-keys
    volumes:
      - "./:/go/src/github.com/cloudposse/github-authorized-keys"
    entrypoint:
      - "sh"
    command: "-c \"while true; do echo 'Hit CTRL+C'; sleep 1; done\""
    restart: always