name: 'goreleaser'

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

  workflow_dispatch:

jobs:
  build:
    name: 'Build Binaries'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Go
      - name: 'Setup Go'
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      # Print Go version
      - run: go version

      # Trial build
      - name: Test build
        if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.ref_name != 'main')
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --config ./dev.goreleaser.yml --clean --snapshot
