name: Release
on:
  release:
    types: [published]

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  perform:
    uses: cloudposse/.github/.github/workflows/shared-release-branches.yml@main
    secrets: inherit
